version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Santosfc@1912
      MYSQL_ROOT_USERNAME: root
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - lokomotimefc:/var/lib/mysql

volumes:
  lokomotimefc: