spring:
  datasource:
    url: jdbc:mysql://localhost:3307/lokomotimefc
    username: root
    password: Santosfc@1912
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port : 8081