spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lokomotimefc
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port : 8080